workflows:
  ios-swift-workflow:
    name: Build iOS IPA
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - DN
        certificates:
          - DN
    scripts:
      - name: Set up Code Signing Profiles
        script: |
          xcode-project use-profiles

      - name: Build IPA via Codemagic CLI
        script: |
          xcode-project build-ipa \
            --project "DNTWEAKS.xcodeproj" \
            --scheme "DNTWEAKS" \
            --archive-flags="CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='iPhone Distribution' PROVISIONING_PROFILE_SPECIFIER='$CM_PROVISIONING_PROFILE_NAME'" \
            --export-options-template="/Users/builder/clone/export_options.plist"

    artifacts:
      - build/ios/ipa/*.ipa
