name: DNTweaks
options:
  bundleIdPrefix: com.yourname
  xcodeVersion: "15.4"
targets:
  DNTweaks:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DNTweaksApp.swift
      - path: Models
      - path: Views
      - path: Components
      - path: Resources
      - path: DucThinh.mobileconfig
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
