import SwiftUI

struct DashboardView: View {
    @EnvironmentObject var themeManager: ThemeManager
    
    let tweaks: [TweakItem] = [
        TweakItem(type: .refreshRate, title: "Display Refresh Rate", icon: "display.2", description: "Demo FPS of internal animations only. Does not change system refresh rate.", isReal: false),
        TweakItem(type: .performance, title: "Performance Profile", icon: "bolt.fill", description: "Changes animation speeds within the app to simulate different performance profiles.", isReal: true),
        TweakItem(type: .pointerSpeed, title: "Pointer Speed", icon: "cursorarrow", description: "UI illustration for iPad pointer speed. No system changes.", isReal: false),
        TweakItem(type: .touchSensitivity, title: "Touch Sensitivity", icon: "hand.tap.fill", description: "Changes gesture recognition threshold in test areas.", isReal: true),
        TweakItem(type: .latency, title: "Input Latency", icon: "timer", description: "Adds artificial delay to app inputs. Simulator - for visualization only.", isReal: false),
        TweakItem(type: .haptic, title: "Haptic Intensity", icon: "iphone.radiowaves.left.and.right", description: "Changes physical haptic feedback generated by the app.", isReal: true),
        TweakItem(type: .battery, title: "Battery Saver", icon: "battery.100.bolt", description: "Reads current system Low Power Mode state.", isReal: true),
        TweakItem(type: .theme, title: "App Theme", icon: "paintpalette.fill", description: "Changes the app's primary accent color.", isReal: true),
        TweakItem(type: .badge, title: "Badge Style", icon: "app.badge.fill", description: "Previews notification badge style.", isReal: false)
    ]
    
    let columns = [GridItem(.flexible()), GridItem(.flexible())]
    
    var body: some View {
        NavigationView {
            ZStack {
                Color.black.ignoresSafeArea()
                
                ScrollView {
                    HeaderView()
                        .padding(.horizontal)
                        .padding(.top)
                    
                    LazyVGrid(columns: columns, spacing: 16) {
                        ForEach(tweaks) { tweak in
                            TweakCardView(tweak: tweak)
                        }
                    }
                    .padding()
                }
            }
            .navigationBarHidden(true)
        }
    }
}
